name: Run organize
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # to interact with the repository files

      - run: ls 
      - run: cd && ls 
      - run: ls ${{ github.workspace }}

      #- run: cd ${{ github.workspace }} && .github/organize_learning.sh

