name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git with GitHub Token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make the organize_repo.sh executable
        run: chmod +x organize_learning.sh

      - name: Update README.md(s)
        run: ./organize_learning.sh

      - name: Configure SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then 
            git remote set-url origin git@github.com:gabrielryanft/learning.git
            git add .
            git commit -m "Auto-update README.md(s) with GitHub Actions"
            git push 
          fi
 
