name: Run organize script
on: [push]
jobs:
  build:
    name: Run organize script script
    runs-on: ubuntu-latest
    steps:
      - run: echo oi > "${{ github.workspace }}/file.txt"
      - run: echo oi > "${{ github.workspace }}/file2.txt"
      - run: ls ${{ github.workspace }}
      - run: echo this is new
