name: Run organize script
on: [push]
jobs:
  build:
    name: Run organize script script
    runs-on: ubuntu-latest
    steps:
      - run: echo oi > "${{ github.workspace }}/file3.txt"
      - run: echo oi > "${{ github.workspace }}/file4.txt"
      - run: for i in ${{ github.workspace }}; do [ ! -d $i ] && cat $i ; [ -d $i ] && echo dir $i ; echo ; done
      - run: ls ${{ github.workspace }}
      - run: echo this is new
      - run: cd ${{ github.workspace }} && cd .. && ls . && pwd
      - run: pwd
